name: Test Coveralls

on: ['push', 'pull_request']

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    # Prevent on version bump
    if: "!contains(github.event.head_commit.author.name, 'Bump version')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn lerna bootstrap --ci
      - run: yarn build
      - run: yarn test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
