name: Test Coveralls

on: ['push', 'pull_request']

permissions:
  contents: read

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    # Prevent on version bump
    if: "!contains(github.event.head_commit.author.name, 'Bump version')"

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3.0.0
        with:
          install: true
          runtime: node@lts
      - run: pnpm nx run-many -t test --coverage.enabled --coverage.reporter=lcov
      - run: node tools/scripts/merge-lcov.mjs
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/lcov.info
