name: Test Coveralls

on: ['push', 'pull_request']

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    # Prevent on version bump
    if: "!contains(github.event.head_commit.author.name, 'Bump version')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - name: lerna bootstrap
        run: npm run npm:lerna bootstrap --ci
      - name: npm build
        run: npm run build
      - name: coverage report
        run: npm run test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
