name: CI

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12']

    name: Node ${{ matrix.node }} build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install
        run: npm ci
      - name: lerna bootstrap
        run: npm run npm:lerna bootstrap --ci
      - name: build
        run: npm run build
      - name: lint
        run: npm run lint
