name: CI

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node LTS build

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: pnpm/setup@v3.0.0
        with:
          install: true
      - uses: nrwl/nx-set-shas@v5
      - run: pnpm nx run-many -t build
      - run: pnpm nx affected -t typecheck
      - run: pnpm nx affected -t lint
